window.BIRD_POSTS = [
  window.EASTERN_WHIP_POOR_WILL_POST,
  window.PROTHONOTARY_WARBLER_POST,
  window.BEAVER_MARSH_TRAILHEAD_POST,
  window.SAND_HILLED_CRANE_POST,
  window.SAW_WET_POST
].filter(Boolean);
